stages:
  - prepare
  - package
  - build
  - analyze

variables:
  BUILD_ENV: build.env
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

default:
  image: maven:3.8-openjdk-17

prepare_job:
  stage: prepare
  script:
    - export VERSION=$(mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec)
    - echo "VERSION=${VERSION}" >> ${BUILD_ENV}
  artifacts:
    reports:
      dotenv: ${BUILD_ENV}
  only:
    - master

quarkus-package:
  stage: package
  script:
    - mvn $MAVEN_OPTS clean install -DskipTests=true
  artifacts:
    paths:
      - target/**
  only:
    - master

docker-build-push:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/src/main/docker/Dockerfile.jvm"
      --destination "${CI_REGISTRY}/cs3/rnd/aero/knative-serverless-controller:${VERSION}"
  only:
    - master

analyze:sonar:
  stage: analyze
  script:
    - mvn $MAVEN_CLI_OPTS $MAVEN_OPTS verify sonar:sonar -Dsonar.qualitygate.wait=true -DskipTests=true
  allow_failure: true
  only:
    - master

