version: '3.7'

services:

  serverless-controller:
    image: registry.ubitech.eu/cs3/rnd/aero/knative-serverless-controller:1.0.4
    container_name: serverless-controller
    restart: unless-stopped
    ports:
      - "9500:9500"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9500/q/health" ]
      interval: 30s
      timeout: 10s
      retries: 5

