quarkus:
  http:
    port: 9500
    cors:
      origins: "*"
      methods: GET, POST, PUT, DELETE, OPTIONS
      headers: "Authorization,Content-Type,Access-Control-Allow-Origin"
      enabled: true
  #      access-control-allow-credentials: true
  smallrye-openapi:
    info-title: knative-serverless-controller
    info-contact-email: info@ubitech.eu
    info-contact-name: UBITECH Ltd.
    info-contact-url: https://ubitech.eu/
  rest-client:
    # Assuming Maestro is running on port 8080
    maestro-rest-api:
      url: http://localhost:8080/
      scope: jakarta.inject.Singleton
  native:
    march: compatibility
  kubernetes-client:
    devservices:
      enabled: false
k8s:
  aero:
    masterUrl: [complete]
    caData: [complete]
    ccData: [complete]
    ckData: [complete]
  local:
    masterUrl: [complete]
    caData: [complete]
    ccData: [complete]
    ckData: [complete]


"%prod":
  quarkus:
    http:
      port: ${QUARKUS_HTTP_PORT:9500}
      cors:
        origins: "*"
        methods: GET, POST, PUT, DELETE, OPTIONS
        headers: "Authorization,Content-Type,Access-Control-Allow-Origin"
        enabled: true
    #        access-control-allow-credentials: true
    smallrye-openapi:
      info-title: knative-serverless-controller
      info-contact-email: info@ubitech.eu
      info-contact-name: UBITECH Ltd.
      info-contact-url: https://ubitech.eu/
    swagger-ui:
      always-include: true
      path: /q/swagger-ui
      enable: true
    rest-client:
      maestro-rest-api:
        url: ${MAESTRO_REST_API_URL}
        scope: jakarta.inject.Singleton
    kubernetes-client:
      devservices:
        enabled: false
    native:
      march: compatibility